### ISSUE TITLE
Cameo 4 Instance DeviceParameter

### ISSUE THREAD

**Issue by yohalmogarcia** [mossblaser/py_silhouette#3]
Not is issue is a suggestion....
This is the object for add support to Cameo 4,
Sorry for my english, Im from El Salvador....
Good day
cameo4 = DeviceParameters(
		product_name='CAMEO4',usb_vendor_id=0x0B4D,usb_product_id=0x1137,area_width_min=inch2mm(3.0),
        area_width_max=inch2mm(12.0),
        area_height_min=inch2mm(3.0),
        area_height_max=inch2mm(40.0),)
[testpysilhouetteCameo4.zip](https://github.com/mossblaser/py_silhouette/files/5681758/testpysilhouetteCameo4.zip)

**Comment by mossblaser** [comment]
Hello there!

Thank you very much for your contribution, I'm very grateful! I have added your changes to the add-cameo-4 branch (PR #4). If all the tests pass with your device I'll merge the changes in and release them.

Thanks agian
